### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by meelten** [coczero/Last.fm-Scrubbler-WPF#1]
Maybe it's a strange question but I have no idea how to launch this application. There is no exe file or anything like that. Do I need some external software? In Last.fm-Scrubbler-WPF folder I see only bunch of "blank" files which I can't open.

**Comment by coczero** [comment]
Sounds like you downloaded the sourcecode.
Download the newest version from this page: 
https://github.com/coczero/Last.fm-Scrubbler-WPF/releases

In that .zip file there is an exe you can start.

**Comment by meelten** [comment]
Oh, indeed. Thanks and sorry for hassle.

**Comment by coczero** [comment]
No problem :)
