### ISSUE TITLE
Album artist

### ISSUE THREAD

**Issue by gebbu** [coczero/Last.fm-Scrubbler-WPF#10]
Would it be possible to add album artist scrobbling functionality like there is on Universal Scrobbler? Album artist is really essential for accurate scrobbling of compilations. Thanks.

**Comment by coczero** [comment]
Yes, I will add this.
Didnt really think about this as I almost never listen to compilations.
But it will be there in the next update.

**Comment by coczero** [comment]
The update is out.
https://github.com/coczero/Last.fm-Scrubbler-WPF/releases/tag/B1.13
