### ISSUE TITLE
Encountered ""Scrobbling '[song name]' failed. Scrobble has been cached." error intermittently

### ISSUE THREAD

**Issue by george-mayday** [coczero/Last.fm-Scrubbler-WPF#101]
Hi, I have encountered this problem intermittently in Last.fm Scrubbler WPF-Beta 1.22.0.0 starting from last week.

When I manual scrobbled a track, occasionally the current status would show "Try to scrobble '[song name]'..." for 10-15s, then change to "Scrobbling '[song name]' failed. Scrobble has been cached."

![Trytocache](https://user-images.githubusercontent.com/71315060/93181960-b21c9380-f76b-11ea-9ec6-96c50c440270.png)
![Errorwhilescrobbling](https://user-images.githubusercontent.com/71315060/93181966-b5178400-f76b-11ea-80c4-6b1caca25032.png)

Same issue was also noted for iTunes Scrobbler (I just use these two functions mainly)

I have already tried the following (found in previous posts) but still not OK
"What fixed it on my end was to log into the Last.fm site, then go to settings > applications settings and disconnect the scrubbler. I then went back to the scrubbler, logged out and back in, and the error was resolved."

Is there any solution for this issue? Thanks a lot!

**Comment by coczero** [comment]
Hmm since it's actually taking a lot of time (10-15s) to show that error message it might really be something with the internet connection. "Usually" tracks only get cached when the track can't be sent to last.fm due to connection problems.
Unfortunately this issue is very hard to debug since I can't reproduce it :(

First thing I would do is to completely remove and redownload the Scrubbler, just to be sure.

**Comment by coczero** [comment]
OK I can reproduce this.
Will have to investigate.

**Comment by george-mayday** [comment]
Thanks!

I already tried to remove and redownload the Scrubbler but still encountered the same issue

**Comment by coczero** [comment]
Can you try if starting the Scrubbler with Admin Rights does anything?

**Comment by george-mayday** [comment]
Hi! I started the Scrubbler with Admin Rights then have used for an hour. All songs can be scrobbled successfully

**Comment by coczero** [comment]
Ok thats good to hear.
Would be very nice if you could observe this for a while :)

**Comment by coczero** [comment]
all good still?

**Comment by george-mayday** [comment]
Hi. I downloaded v1.23 and problem has not been encountered again.

**Comment by coczero** [comment]
Okay, just notify me when it happens again.
