### ISSUE TITLE
2 questions about this app

### ISSUE THREAD

**Issue by bluemelodypp** [coczero/Last.fm-Scrubbler-WPF#11]
First, thanks for this amazing app. 
I have 2 problems:
Q1. When I double click the song in iTunes, the scrubbler runs ok, but when one song is over, the next song that is automatically played is not scrobbled.

Q2.How can I use this app to scrobble my iPod classic? 

Really appreciate it!

**Comment by coczero** [comment]
Hey, thanks for your feedback.
Q1: this is a bug and will be fixed in the next release. Thanks for reporting!
Q2: This is currently not possible with this app. I will look into it on how to do it, but it is kinda hard. Can't say for sure if it will be ever possible.

**Comment by bluemelodypp** [comment]
Last.fm official app is not working any more with my iTunes, your app saves my ass!!!
If this app can scrobble my iPod please tell me! Thanks again!

**Comment by coczero** [comment]
Hey, the update is out. 
You can download it here: https://github.com/coczero/Last.fm-Scrubbler-WPF/releases/tag/B1.14
If you find any more issues, let me know!

**Comment by bluemelodypp** [comment]
It works!!!! Thanks!

**Comment by hans-juergen** [comment]
By the way, does it also scrobble streamed songs from Apple Music, or only local files being part of the usual iTunes library?

**Comment by coczero** [comment]
I actually haven't tested this, because I don't use apple music.
It works with via iTunes events like "song started to play" so in theory it could work. But I don't know how Apple Music works so it would need testing.

**Comment by bluemelodypp** [comment]
One more question, does it scrobble from windows media player?

**Comment by coczero** [comment]
Not currently, but thats on my todo list.

**Comment by bluemelodypp** [comment]
Thanks!!! Expecting for your updates!!
