### ISSUE TITLE
Load Button in CSV

### ISSUE THREAD

**Issue by Bucketsatch** [coczero/Last.fm-Scrubbler-WPF#14]
Hello !
Pretty amazing app!!

The thing is that i'm trying to import my scrobbles from an old last.fm account. I have the needed CSV file on from my computer but the load button does not work.
![a](https://user-images.githubusercontent.com/29406764/27089592-7edaeed4-5063-11e7-9cd3-0731897e8fbd.jpg)

Your help will be much appreciated!

**Comment by coczero** [comment]
Hey, that version youre using looks preeety old 😄 
You should update to the last version you can download it here: https://github.com/coczero/Last.fm-Scrubbler-WPF/releases/tag/B1.14

**Comment by Bucketsatch** [comment]
Done! Still same issue :/

**Comment by coczero** [comment]
It should look different now. There shouldnt be a load button anymore.

**Comment by Bucketsatch** [comment]
Yes sure! I just can't have access to the file path.

![aa](https://user-images.githubusercontent.com/29406764/27091968-6f4c885e-506a-11e7-840c-1611a9428c58.jpg)

**Comment by coczero** [comment]
So absolutely nothing happens when you press the "..." button?

**Comment by Bucketsatch** [comment]
Exactly! It's kind of loading for less than half a second but nothing happens. The same goes for "add files" button in the File Scrobble section.

**Comment by coczero** [comment]
Hmm I cant really seem to reproduce this issue... can you try deleting the whole program folder and downloading it again? Maybe some file got corrupted. Otherwise try it on a different machine.
Or maybe the dialog is opening in the background so maybe try clicking the button then moving the window around to see if the dialog popped up behind it.

**Comment by coczero** [comment]
Also, could you please run Windows Update? I know it sounds odd but I just read that there were cases where a missing update (especially SP1 KB976932) caused dialogs not to show.

**Comment by Bucketsatch** [comment]
Indeed, it was a missing windows update that was causing this issue! Thanks a lot coczero !!

**Comment by coczero** [comment]
Glad to hear it's working :)
