### ISSUE TITLE
Problems with very long CSV files

### ISSUE THREAD

**Issue by hans-juergen** [coczero/Last.fm-Scrubbler-WPF#2]
Hi, I just tried to import my complete Last.fm listening history obtained from the online tool Last.fm to csv in your app. It took several minutes for almost 240k scrobbles which is OK, but it seems that I cannot select single or all scrobbles in the list afterwards, trying to check the marks does nothing. Is there a maximum limit for imported scrobbles perhaps? Sorting the columns alphabetically neither works, by the way.

**Comment by coczero** [comment]
Hi, there should be no limit to the amount of scrobbles. My guess is that you are not in "Import Mode" when using the CSV Scrobbler. As you can only import scrobbles newer than 14 days, there is a specific mode for CSV scrobbling that basically ignores the timestamp of the original scrobble. That way you can import scrobbles from csv that are older than 14 days. If switching to Import Mode still does not fix your problem, I'd be glad if you could send me your csv so I can test myself.

**Comment by hans-juergen** [comment]
You're right, I did not realise that I had to change to Import Mode at the bottom first before actually opening the 20 MB CSV file. Now it works, great.

But sorting the columns of the imported list is not possible, or is it? And can I also use your app to scrobble the imported tracks to another account of mine? That would afford changing the login on the fly somehow.

**Comment by coczero** [comment]
Glad it works now. I will look into the sorting stuff, that should definitely work. 
Your other question, do you mean scrobbling to multiple accounts at once?

**Comment by hans-juergen** [comment]
No, just switching to another when you realise you're logged into the wrong one. But as mentioned this is not necessary if you just close the app and relogin where you actually want to scrobble.

**Comment by coczero** [comment]
It actually is not a bad idea! I might add that. But you don't have to close the app, you can just relog when you click your Username in the bottom left.

**Comment by hans-juergen** [comment]
OK, that option would be enough for me if it still lists the imported CSV file afterwards. :-)

**Comment by coczero** [comment]
Relogging should have no effect on any data in the different scrobble tabs :)
