### ISSUE TITLE
iTunes playcounts don't update when Scrubbler is running

### ISSUE THREAD

**Issue by danmam** [coczero/Last.fm-Scrubbler-WPF#22]
Hi, and thanks for the effort you've put into getting the Scrubbler working while Last.fm's official Scrobbler still can't function with iTunes 12.7. I'm running Windows 10, and have iTunes 12.7.0.166, and when I have both iTunes and the Scrubbler open, when a track finishes playing in iTunes, it is successfully scrobbled (at the 50% play point), but the play count on iTunes doesn't update. Anyone else experiencing this issue? Is there a possible fix for it?

Thanks!

**Comment by coczero** [comment]
This has nothing to do with the scrubbler. It is an iTunes bug. Therefore there's nothing I can do.

**Comment by danmam** [comment]
Thanks for quick response -- no problem, keep up the great work.
