### ISSUE TITLE
CSV import

### ISSUE THREAD

**Issue by myrdingar** [coczero/Last.fm-Scrubbler-WPF#23]
Hi.
I have a csv with all my tracks. I load the file, but when I click parse, I got an error parsing rows. Some rows could not be parsed and ask me to create a log file. I do not understand where my error is. Thank you

**Comment by coczero** [comment]
Well what does the logfile say?

**Comment by myrdingar** [comment]
I report one line as example:
CSV line number: 2,Omnium Gatherum;Grey Heavens;Skyline;12/10/2017 21:47,Indice oltre i limiti della matrice. (Index beyond limits of matrix)

**Comment by coczero** [comment]
Please send me your CSV file so I can debug this.

**Comment by myrdingar** [comment]
Here they are! Thank you!

[row.txt](https://github.com/coczero/Last.fm-Scrubbler-WPF/files/1383626/row.txt)

[Scrobbling Lastfm totale.zip](https://github.com/coczero/Last.fm-Scrubbler-WPF/files/1383657/Scrobbling.Lastfm.totale.zip)

**Comment by coczero** [comment]
Hi please try the following version: 
[Debug.zip](https://github.com/coczero/Last.fm-Scrubbler-WPF/files/1384581/Debug.zip)

Please note how to proceed:
- Go to CSV Parser
- Open the settings
- Set delimiters to only ;
- Save

Your csv should parse fine.
Please do note that this is a beta build with some functionality not ready for the public.

**Comment by myrdingar** [comment]
Wonderful! It worked at last!
Thank you again for your time and support.
