### ISSUE TITLE
Minimizing/closing the app

### ISSUE THREAD

**Issue by asundersweet** [coczero/Last.fm-Scrubbler-WPF#25]
Just a quick idea to make using Scrubbler more comfortable:

Make it so Scrubbler is minimized to the system tray when you click the close or minimize button. That way it doesn't sit around in your taskbar all the time. Also, make it possible to run Scrubbler minimized on startup, just like the official Last.fm scrobbler. Great app otherwise!

**Comment by coczero** [comment]
Nice ideas! Not sure if it will be in the next version though.

**Comment by coczero** [comment]
This is now implemented and will be part of the next release
