### ISSUE TITLE
How i run the app?

### ISSUE THREAD

**Issue by CristinaRL** [coczero/Last.fm-Scrubbler-WPF#26]
Hi, maybe it is a bit dumb question but i don't know how exactly i have to run the app. I don't know if i'm downloading the wrong things but i don't find it.

Thanks in advance :)

**Comment by coczero** [comment]
Hi, just download the most recent release from [this](https://github.com/coczero/Last.fm-Scrubbler-WPF/releases) page. In the downloaded zip file is a .exe you can run.

**Comment by CristinaRL** [comment]
Thank you so much!
