### ISSUE TITLE
CSV Scrobbler does not register album field

### ISSUE THREAD

**Issue by thcrack** [coczero/Last.fm-Scrubbler-WPF#29]
This has been an issue since I started using. For some new albums that don't have their song list on last.fm database yet, I can only download my whole csv record, select previous scrobbles of the same album and scrobble them again via CSV scrobbler, but the result seems to ignore the album field even though it's correctly previewed.

![2018-01-16_234947](https://user-images.githubusercontent.com/14831470/34997758-36d3e108-fb18-11e7-9e9c-40051332b09f.jpg)
![2018-01-16_235052](https://user-images.githubusercontent.com/14831470/34997759-36ff5f0e-fb18-11e7-84fc-3bd71aa7bc32.jpg)
![2018-01-16_234934](https://user-images.githubusercontent.com/14831470/34997760-3726d412-fb18-11e7-9d79-d486bc85baca.jpg)

**Comment by coczero** [comment]
Oh, youre right.
This is fixed now.
I try to push a new release today.
Thanks for reporting!

**Comment by coczero** [comment]
1.16 is released now. Download it [here](https://github.com/coczero/Last.fm-Scrubbler-WPF/releases/tag/B1.16)
