### ISSUE TITLE
Direct import of local media databases (iTunes, WMP, Winamp, foobar)

### ISSUE THREAD

**Issue by hans-juergen** [coczero/Last.fm-Scrubbler-WPF#3]
Sorry for spamming you with ideas, but it would be great if your app could directly import the databases of local media players, because then it would be possible to scrobble them in bulk to Last.fm. This would of course mean that you lose the original time stamps of the played songs, but could be a good substitute for the missing bootstrapping option on the new Last.fm site which did not show the original time stamps either.

**Comment by coczero** [comment]
Haha no worries, I gladly take all ideas! :) 
Very good idea, but I have no experience in the structure of the media databases.
I will take a look into it and see if it is doable for me! :)

**Comment by hans-juergen** [comment]
That would be great, see e.g. this new thread on the Get Satisfaction support forum from a returning user who would like to scrobble what he has listened to in the meantime:

https://getsatisfaction.com/lastfm/topics/i-stopped-using-last-fm-for-a-few-years-just-re-started-any-chance-the-plays-in-the-interim-will

**Comment by coczero** [comment]
I just parse the itunes .xml that you can generate in itunes. 
I will make my csv parser better in the future then people can also use the csv created with the methods you listed. The feature (atleast Itunes) will be finished in the next few days.

**Comment by coczero** [comment]
iTunes is now implemented.

**Comment by hans-juergen** [comment]
Great, I just created a new thread on Get Satisfaction in the API and Scrobbling Apps categories:

https://getsatisfaction.com/lastfm/topics/new-last-fm-scrubbler-1-5-can-import-itunes-database

By the way, usually Last.fm ignores scrobbles shorter than 30 seconds, so did you test your default value of 1 second if it really works? If not, you should raise the default value to 30 seconds.

**Comment by coczero** [comment]
I thought the same about the 30 seconds, but I tested a lot and it seems to not make any difference. When you manual scrobble, you don't give the length of the song, you only give the length between two scrobbles, where 1 second seems to be fine.

**Comment by coczero** [comment]
WMP is now implemented
