### ISSUE TITLE
CSV Importing wrong / not working correct scrobble data

### ISSUE THREAD

**Issue by Gelo3D** [coczero/Last.fm-Scrubbler-WPF#32]
V: 1.16.0.0 

Short info : CSV scrooble time doesnt work correct, insert today date for all rows of scrooble

Screenshots : 

![obraz](https://user-images.githubusercontent.com/15075411/35479657-f3e78082-03fc-11e8-98a2-521e9aab2e4f.png)
![obraz](https://user-images.githubusercontent.com/15075411/35479666-29701250-03fd-11e8-96d8-5e5c6f35ad03.png)
![obraz](https://user-images.githubusercontent.com/15075411/35479681-72766d5a-03fd-11e8-8f46-a51410b6c397.png)
![obraz](https://user-images.githubusercontent.com/15075411/35479688-9becc8a0-03fd-11e8-9ecb-bfc4588b83b4.png)
![obraz](https://user-images.githubusercontent.com/15075411/35479691-a1ade21a-03fd-11e8-9e21-f4b0470008c4.png)

**Comment by coczero** [comment]
Are you using "ImportMode" or "Normal" as Scrobble Mode?
Import Mode will always scrobble with the current / set DateTime.
If you want to use the Timestamp from the csv file you need to use Normal mode

**Comment by Gelo3D** [comment]
Omg :( to late but thx for response next time i use normale mod but why importmode is default ? 
Peoples usually use imprt mode not normal  ?

**Comment by coczero** [comment]
People usually use import mode yes, its more common to get a csv from for example an old media player library or so.
