### ISSUE TITLE
Fatal error while scrobbling

### ISSUE THREAD

**Issue by fromis** [coczero/Last.fm-Scrubbler-WPF#33]
![screenshot_39](https://user-images.githubusercontent.com/36209760/35884816-c1b1071c-0b83-11e8-88fb-083312639533.png)

**Comment by coczero** [comment]
I am going to need some more info, since I can't reproduce this.
- Scrubbler Version
- iTunes Version
- Does the track you play have an AlbumArtist field?
- Are all tracks affected or only some?

**Comment by fromis** [comment]
*   Scrubbler Version: 1.16
  *   iTunes Version: 12.7.3.46
  *   Does the track you play have an AlbumArtist field? Yes
  *   Are all tracks affected or only some? So far it's only worked on songs I've bought through iTunes (not on Apple Music)

Thanks!

________________________________

**Comment by coczero** [comment]
Ok so I tried to fix this, and it should scrobble now, but I couldn't reproduce it.
Can you send me one of your music files where scrobbling doesnt work so I can test with it?

**Comment by coczero** [comment]
Closed because no further information
