### ISSUE TITLE
Scrobbling

### ISSUE THREAD

**Issue by lifebeforelove** [coczero/Last.fm-Scrubbler-WPF#34]
Is it possible to scrobble more than 500k scrobbles? I have 550k and I was trying to scrobble it to a new account, but it stops working everytime I try to do so.

**Comment by coczero** [comment]
What exactly do you mean with 'stops working'?
Does the app crash or display an error message, or does it just not work?
In theory there is a scrobble limit, tho I've never seen it work in practice.

If you want, you can send me the file you're trying to scrobble so I could try to reproduce.
In the meantime you could split the file into multiple files and see if that works.

**Comment by lifebeforelove** [comment]
It just doesn't work. I tried doing it again a few times and it's still the same. I even waited a few minutes to see if it would work, but no success.
I also tried doing it with multiple files, still didn't work.

**Comment by coczero** [comment]
Can you send me the file?

**Comment by lifebeforelove** [comment]
I tried splitting the files again and it worked, just had to select 10k per package. Thank you anyways!

**Comment by coczero** [comment]
Closed because no further information
