### ISSUE TITLE
how do i install?

### ISSUE THREAD

**Issue by henrichnq** [coczero/Last.fm-Scrubbler-WPF#35]
i'm sorry for the dumb question but i really dont know what to do, please help!

**Comment by coczero** [comment]
You have to download a Release, then extractor that, there will be a exe file you can execute

**Comment by henrichnq** [comment]
yeah i downloaded, but i cant find the exe file, whats the name?

**Comment by coczero** [comment]
Did you Download from here: https://github.com/coczero/Last.fm-Scrubbler-WPF/releases/tag/B1.16?

**Comment by henrichnq** [comment]
no, thanks, it worked now!! thank you so much
