### ISSUE TITLE
Error when connecting to iTunes

### ISSUE THREAD

**Issue by delta25** [coczero/Last.fm-Scrubbler-WPF#39]
Hiya, I'm getting an error when trying to connect to iTunes. The window's status bar is too small for me to read the entire thing, but hopefully the first part of the stack trace is enough.

Error connecting to itunes: Unable to cast COM object of type 'System._ComObject' to interface type 'iTuneLib.itunesApp'. This operation failed because the QueryInterface call on the COM component for the interface with IID [long GUID here] failed due to the following error: No such

That's all i got i'm afraid. If you write your logs somewhere let me know and i'll look for it.

**Comment by coczero** [comment]
Hi, could you try to use the prerelease 1.17 found here: https://github.com/coczero/Last.fm-Scrubbler-WPF/issues/36

**Comment by delta25** [comment]
Nope. Didn't help i'm afraid. I'm running windows 10 and iTunes 12.7.3.46

**Comment by delta25** [comment]
Apologies are in order on my end. That fixed it. Wasn't aware that I was
behind a couple of versions!

Issue resolved.

Thanks. :)
