### ISSUE TITLE
Spotify scrobbling with their desktop app not working

### ISSUE THREAD

**Issue by hans-juergen** [coczero/Last.fm-Scrubbler-WPF#40]
Hi, I just tried to scrobble the Spotify desktop client with your app for the first time due to current problems. It does not work for me (Scrubbler v1.16, Windows 10 64-bit, Spotify v1.0.75), neither with local files nor with streamed tracks e.g. from my Discover Weekly playlist. The Current Status line says "Error while scrobbling: CacheFailed" for any song while artist and track title are correctly recognised and the Scrobble-Meter progress bar also seems to work. When checking the Scrobble Cache tab, it is empty.

**Comment by coczero** [comment]
Could you try if it works with the prerelease 1.17 found here: https://github.com/coczero/Last.fm-Scrubbler-WPF/issues/36

**Comment by hans-juergen** [comment]
I tried it with v1.17 (which still says "1.16" in the header) got the same error message in Current Status when scrobbling my Discover Weekly playlist. Album cover, track, artist and album title are correct though.

**Comment by coczero** [comment]
Weird, the header says 1.17 for me. Are you sure you've overwritten the old files correctly? I recommend deleting the old scrubbler before using the new one.

**Comment by hans-juergen** [comment]
OK, I was sure that I had overwritten the *.exe file yesterday with the usual "extract all" option of Windows 10, because I checked the file date which said 09.05.2018. But for some odd reason it obviously still was v1.16. After deleting all files in the Scrubbler subfolder and extracting again, I could start v1.17 (had to use admin rights though, or it would not create hjbardenhagen.db in the Debug folder).

Anyhow, now I'm scrobbling while streaming with the Spotify desktop client 1.0.75 and no other scrobbler active (no Last.fm beta scrobbling, no internal Spotify scrobbling). Next check will be my local files.

**Comment by hans-juergen** [comment]
Hmm, some bad news: scrobbling while streaming already stopped after 3 songs like yesterday. The Scrubbler is stuck showing me the third song while still being connected to Spotify, or at least it thinks so. Trying to reconnect gives this error: "Fatal error connecting to Spotify: Der Remote-Server hat einen Fehler zurückgegeben: (503) Server nicht verfügbar."

So maybe it is caused by temporary problems with the Spotify Web API.

**Comment by coczero** [comment]
I have used Spotify scrobbling recently and it actually worked quite well, but I have no ads so that might be the problem. I will have to investigate further, thanks for the information so far

**Comment by coczero** [comment]
Yea, unfortunately the spotify api does not communicate local album information for whatever reason :/

**Comment by hans-juergen** [comment]
I noticed recently that you cannot click on artist or album in your local files anymore (all greyed out now) which was still possible not long ago.  So they seem to have changed something not only in the desktop client, but in general.

I think the browser extension Last.fm web scrobbler uses Last.fm's database instead when it cannot find album info for the current track. Furthermore you can also edit the scrobble before it gets submitted, so you could add album info manually at least or edit a spelling error.

**Comment by coczero** [comment]
As far as I can tell this seems to be a bug in the spotify api wrapper I am using. Because I actually do check for ads, but apparently the ad detection of the api wrapper is broken (already reported)

**Comment by hans-juergen** [comment]
I see, as far as I remember there was a similar problem with Spotify ads stopping playback when the Spotify Player on Last.fm was new. Hopefully they can fix their wrapper, as the Scrubbler could be a good alternative for users who do not like the new Last.fm feature of Spotify scrobbling. If you also add iPod scrobbling, you could probably earn money with it. ;-)

**Comment by hans-juergen** [comment]
It stops scrobbling after each Spotify ad, but clicking on Reconnect resumes the scrobbling, so it is the same behaviour as before.

**Comment by coczero** [comment]
The local spotify scrobbling is dead at the moment. Read this for further information: https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/254
