### ISSUE TITLE
Changing "time played" cursor problem

### ISSUE THREAD

**Issue by Alsweider** [coczero/Last.fm-Scrubbler-WPF#42]
When I change the minute or hour of "time played" in the manual scrobbler by clicking on the up/down arrows or scrolling the mouse wheel, the cursor switches at the second number from minute to day, so I have to click again on the minute after every number. Version is 1.17.0.0.

**Comment by coczero** [comment]
Nothing I can do about this right now, I will have to wait for a bugfix of the Xceed.WPF Toolkit
