### ISSUE TITLE
App stops doing its job when minimized to the tray

### ISSUE THREAD

**Issue by asundersweet** [coczero/Last.fm-Scrubbler-WPF#43]
This is an issue in the newest beta version. In iTunes scrobbling, whenever I minimize Scrubbler to the tray, the "scrobble-meter" stays at the position it was last in and the song ends up not being scrobbled. I have to reconnect to iTunes for the app to start scrobbling again, and when I minimize it the error persists.

**Comment by coczero** [comment]
Thank you for reporting. I will investigate this.

**Comment by coczero** [comment]
I have identified the cause of this error and am currently working on a solution.

**Comment by coczero** [comment]
Fixed by https://github.com/coczero/Last.fm-Scrubbler-WPF/commit/0f1e3373746476995c38170db516f8754a8c081d

**Comment by asundersweet** [comment]
Thank you for your work!
