### ISSUE TITLE
"Log in" doesn't work

### ISSUE THREAD

**Issue by RinettaW** [coczero/Last.fm-Scrubbler-WPF#44]
The problem appeared after updating Windows. So basically when I click "Not logged in" button and then "Add a new customer" and put my Last.fm name and password I get a window with message "Failed to log in or authenticate!". 
Tried to reopen the programm, checked login and password, even tried to restart my computer. The message still appears. 
![screenshot_1](https://user-images.githubusercontent.com/40003410/41057597-32f75a34-69d0-11e8-9470-e24e61d2a50e.jpg)

**Comment by coczero** [comment]
Please update to the 1.18 release it will work with that
