### ISSUE TITLE
Error while scrobbling

### ISSUE THREAD

**Issue by Garellos** [coczero/Last.fm-Scrubbler-WPF#45]
Hi,

suddenly the Scrubbler stopped working on my PC. I used version 1.15 on Windows 10, Version 1803 and iTunes is on Version 12.7.5.9.

It tries to scrobble, but fails, instead there's an error message: "Error while scrobbling" alternating with "Trying to scrobble". Also it never loads the album cover.
Afterwards the Scrubbler shuts down and I can't even restart it.

Now I've tried Scrubbler version 1.17, but there I can't even log in: "Failed to log in or authenticate!"

It has worked fine for months, suddenly these issues appear without me changing anything.

**Comment by coczero** [comment]
Download the 1.18 release.
