### ISSUE TITLE
Error connecting to itunes

### ISSUE THREAD

**Issue by jeremymeyers** [coczero/Last.fm-Scrubbler-WPF#46]
(using 1.18)

When hitting the connect button, i get the following:

"error connecting to itunes: unable to cast COM object of type 'System._ComObject' to interface type 'iTunesLib.iTunesApp'. This operation failed because Queryinterface call on the COM component for the interface with IID {96DD66808-3EDC-A771-E6FE4832E34A} failed due to the error" (and then i run out of room on the window)

using iTunes 12.7.5.9

![screenshot 2018-06-10 22 32 08](https://user-images.githubusercontent.com/3514095/41210212-4e6254b4-6cfe-11e8-9dbb-80e0a898a8bb.png)

**Comment by jeremymeyers** [comment]
(also might be time for a function to generate an error log)

**Comment by coczero** [comment]
You can hover over the status text to show a tooltip with the whole error message

**Comment by coczero** [comment]
(But yes, I agree, there should be logging functionality)

**Comment by jeremymeyers** [comment]
using tooltip it says the error is "library not registered" but since tooltips don't wordwrap thats the furthest i can get :/

**Comment by jeremymeyers** [comment]
using 0.19, the log.txt shows this:

[7/30/2018 8:28:12 P]: Error connecting to iTunes: Unable to cast COM object of type 'System.__ComObject' to interface type 'iTunesLib.iTunesApp'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{9DD6680B-3EDC-40DB-A771-E6FE4832E34A}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).

**Comment by coczero** [comment]
Sorry I don't really know what the problem is, but it has nothing to do with the Scrubbler.
It is either a corrupt iTunes installation or a registry problem. See some more info [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/08f13e9d-895c-4102-b6d9-e327af8cf8c0/0x80029c4a-typeecantloadlibrary?forum=vsto) or [here](https://sourceforge.net/p/ita/discussion/498575/thread/f267747f/)

**Comment by jeremymeyers** [comment]
Can confirm this. the Microsoft.com link helped.

Steps to fix (for posterity and in case it comes up for others):
- Search for and delete any instances of the above registry key with regedt32.exe
- Uninstall both 32-bit and 64-bit "Apple Application Support"
- Uninstall iTunes
- Restart
- Reinstall iTunes (i used the 64 bit version from http:/www.apple.com/itunes/download

**Comment by george-emerald** [comment]
Hey, could you tell me where is that registry key? Also, I don't have "Apple Application Support", is it no longer in use or am I not finding it?

**Comment by jeremymeyers** [comment]
Having this happen again. Possibly will happen every time iTunes updates? To be specific, I have iTunes installed from the Microsoft App Store.

**Comment by coczero** [comment]
@jeremymeyers I am on iTunes 12.9.4.102 and have no problems to connect to it.
Might be a problem of the store app. Can you try with the desktop version?

**Comment by anyhowes** [comment]
Am on Version 12.9.5.7 and experiencing the same issues. Will look into the uninstall, reinstall directly from iTunes website instead of windows store and report back.
