### ISSUE TITLE
I'm confused! How does it work?

### ISSUE THREAD

**Issue by Bardinova** [coczero/Last.fm-Scrubbler-WPF#5]
Sorry for my lame question, but it doesn't work! I want to use this app because it seems that my iTunes doesn't like the official scrobbler anymore. So, I logged in and in front of the "Current Status:" the"Waiting to Scrobble" appears. But the "Scrobble" bottom is still off and I don't know what to do to make it work. So please help me how can I use this app?

**Comment by coczero** [comment]
You already closed this, so I guess you already figured the answer out :D 
I'm gonna answer anyways, for future reference. This is a manual scrobbler, meaning you have to input the data you want to scrobble yourself. For example when you are listening to a CD on a CD Player, you can use this app to scrobble it. There is no "automated" way to scrobble for example iTunes (although this is kinda on my to-do list)
