### ISSUE TITLE
Add plain text bulk scrobble copypasted from text buffer

### ISSUE THREAD

**Issue by Axolotl3d** [coczero/Last.fm-Scrubbler-WPF#51]
Scrobble by direct copypasting from text buffer with some simple format like "Artist - Track"
Something like this:

Joan Baez - It's All Over Now, Baby Blue
Blaine L. Reininger - Jacob's Ladder
Laura Marling - Old Stone
The Doors - Twentieth Century Fox
Ty Segall - My Head Explodes

"Universal Scrobbler" have such feature but it's not a free service.

**Comment by hans-juergen** [comment]
You could save your text file and/or copy & paste your text buffer as CSV in a spreadsheet app and import that with the Scrubbler.

**Comment by coczero** [comment]
Raw text brings it's own share of problems with it, I think it would be better to just use csv files.
