### ISSUE TITLE
App crashes when date in the past is selected

### ISSUE THREAD

**Issue by Offerel** [coczero/Last.fm-Scrubbler-WPF#52]
When I use "File Scrobbler" and choose a date in the past as "Finishing time", the app crashes.

**Comment by coczero** [comment]
Hi thank you for reporting this bug. I could reproduce it.
Though the app does not crash when you select a date in the past but rather when a specific part of the date is selected and you try to click on one of the up/down arrows.
This is a bug in the Xceed.Wpf.Toolkit so I can't really fix it.
I might find some kind of workaround.

**Comment by coczero** [comment]
Actually Xceed has fixed this in v3.5, but that isn't released yet

**Comment by Offerel** [comment]
My main problem is, that i want to switch from MediaMonkey to MusicBee Music Manager on Windows and maybe something other on Linux. I could rescan my library folder to add a new library, but since it's a very huge library, i do not will update PlayCount and timestamps by hand for every song. So, my idea was it to use Last.FM as some sort of middleware to transport this data, exporting the timestamps to Last.FM and importing them to the new music manager. I could export MediaMonkey Library as iTunes XML file but found no way to use this as import for timestamps and playcounts. Than i found your app. 

If i use "MediaPlayer Database Scrobbler", the timestamps are translated to the actual date. So i can't use this. This would be the easiest way for me. "File Scrobbler" was only the workaround for me :-)

**Comment by coczero** [comment]
Mediaplayer Database Scrobbler has an import mode where you can set the timestamps manually. Keep in mind though that last.fm only allows scrobbles with dates newer than two weeks, anything older will be ignored.

**Comment by Offerel** [comment]
Ohh, thats bad. I didn't know that. Than i cant go this way. Some timestamps are older than 2 years. Il try to find a way to import directly from the iTunes library.
