### ISSUE TITLE
Sorting by "Last played" not possible

### ISSUE THREAD

**Issue by langemike** [coczero/Last.fm-Scrubbler-WPF#53]
When using the Media Player database scrobbler I like to be able to sort my imported database by "Last played". But when pressing this column it won't sort or do anyhting... I think this is due to an issue regarding the Date format.

Besides that, it will also be handy if I have selected multiple record to check them in 1 go. The UI won't allow me to do that. So i have to check each record manually. Which could get a little repetative after a while ;)

As you could probably notice by this request. I would like to be able to scrobble the play counts of the tracks i played last year. As  I have everything scrobbled before that time period.

Thanks. Awesome application BTW :)

**Comment by coczero** [comment]
Thanks for reporting. I will take a look.
The multi select thingy is already planned =)

**Comment by coczero** [comment]
Fixed the LastPlayed sorting
