### ISSUE TITLE
Minor: rename "ITunes Scrobbler" tab to "iTunes Scrobbler"

### ISSUE THREAD

**Issue by patrickhlauke** [coczero/Last.fm-Scrubbler-WPF#58]
A silly little request, but for some reason it irks me every time I see it... (had a naive look through the repo's source, but can't seem to find the place where the name of the tab interfaces is set...)

> ![capture](https://user-images.githubusercontent.com/895831/45601996-f4d8f300-ba0d-11e8-88d0-235c0151ed6f.PNG)

**Comment by coczero** [comment]
Now that I noticed it, it really is kind of annoying =D
Fixed in https://github.com/coczero/Last.fm-Scrubbler-WPF/commit/746a0a8f0fdeeaa6985125cb5523a425635915fe

**Comment by patrickhlauke** [comment]
perfect, thank you 👍
