### ISSUE TITLE
Stuck in "trying to scrobble"

### ISSUE THREAD

**Issue by escruting** [coczero/Last.fm-Scrubbler-WPF#6]
I parse the itunes xml successfully. I select a track and press scrobble. But it gets stuck on "trying to scrobble selected tracks"

**Comment by coczero** [comment]
Do you really only select one track or do you select multiple tracks? Depending on the amount of scrobbles it can take a long time.

**Comment by escruting** [comment]
It does the same selecting just one or mutliple tracks.

**Comment by coczero** [comment]
Could you try if you have the same problem for the other scrobblers (for example the ManualScrobbler) ?

**Comment by escruting** [comment]
It scrobbled successfully in manual mode.

**Comment by coczero** [comment]
ok that is weird. which version do you use? 1.6 or 1.7?

**Comment by escruting** [comment]
1.6 is the last one published publicly -->https://github.com/coczero/Last.fm-Scrubbler-WPF/releases

**Comment by coczero** [comment]
Oh, I forgot haha.
I will look into it.

**Comment by escruting** [comment]
Okay, thanks very much. Also, when i manually scrobbled, the media player db scrobble tab became unresponsive, all the buttons were grey and couldn't do anything until i reopened again the application.

**Comment by coczero** [comment]
Was the MediaDB scrobbler trying to scrobble while you scrobbled via the ManualScrobbler?

**Comment by escruting** [comment]
Yes, possibly... i left the app opened and now i see it finally scrobbled the mediaDB... but it scrobbled the track 100k times :D

**Comment by coczero** [comment]
I am so sorry, I just found the bug, I accidentally left some old test code in :(
I hope I did not screw your account... :S

**Comment by escruting** [comment]
It scrobbled 35k times each track i tried to scrobble, but i tried each of those individually.

**Comment by coczero** [comment]
It is fixed in the newest releas 1.7 ... https://github.com/coczero/Last.fm-Scrubbler-WPF/releases
So sorry for the inconvenience

**Comment by escruting** [comment]
It wouldnt be a problem if lastfm didnt remove being able to erase a track completely, now its only possible to delete tracks scrobble by scrobble. Don't worry, you put up a warning on your app description, it was me who disregarded it.

**Comment by coczero** [comment]
Still, it was entirely my fault. I will look at the last.fm api and see if there is way to delete scrobbles programmatically. Because I heard that complaint about not being able to remove more tracks a lot of times now. There is also this: http://blog.thomasupton.com/2012/08/batch-deleting-last-fm-scrobbles/

**Comment by escruting** [comment]
Okay dude, i hope you find a way.

**Comment by hans-juergen** [comment]
I still have this bookmark of a Japanese tool to delete duplicate scrobbles from your library, but have no idea if it still works with the new site:

http://meaw.kagechiyo.net/web/RemoveDuplicatedTrack.eng.html

**Comment by coczero** [comment]
Didnt actually try the site, but it was atleast be able to find some duplicate scrobbles so I would guess it works. I will still implement a track remover in my app.

**Comment by escruting** [comment]
I tried it but it gives me "code:3
Invalid Method - No method with that name in this package" when i press the "remove" button,

**Comment by escruting** [comment]
The code on this site http://blog.thomasupton.com/2012/08/batch-deleting-last-fm-scrobbles/ is working fine, i just need 1-2 hours per song.

I tried your 1.7 beta and it is working fine, it scrobbles just the play count the song was listened (yay) and i can select multiple songs. 
Thanks for your app, i think i will be using it until the official lastFM desktop scrobbler supports 64bit iTunes.

**Comment by hans-juergen** [comment]
> I tried it but it gives me "code:3
Invalid Method - No method with that name in this package" when i press the "remove" button,

Right, I got the same after it had found over 400 duplicates in my library. So the Delete function in his tool is broken for some reason, but it is still able to find and list them. If you open your library pages from the search result, it is very easy to delete the duplicates manually there. For example there obviously were general database issues on Nov 25, 2012 and Jul 16, 2013 where all tracks appeared four or five times in your library.

**Comment by coczero** [comment]
About the scrobble remove functionality:
Unfortunately there is no easy way to do it programmatically. The individual scrobble remove and whole track remove API have been removed. Therefore the only way I can think of is mimic the POST request when manually deleting a scrobble. This will take some time.

**Comment by ljcool2006** [comment]
I'm still having this problem.
