### ISSUE TITLE
Crash on VM when parsing cvs

### ISSUE THREAD

**Issue by rootion** [coczero/Last.fm-Scrubbler-WPF#60]
Using v. 1.19.0.0 in a VM with windows 10 with assigned 8GB ram in a mac osx host.
I am trying to parse a large csv, but the software is stuck in not responding and it will close itself after a while without parsing anything. Is there a way to debug this?

**Comment by lucianasena** [comment]
I'm not using a VM, but I'm having exactly the same problem. I'm also using Windows 10.

**Comment by coczero** [comment]
Please upload the csv files you are using

**Comment by lucianasena** [comment]
> Please upload the csv files you are using

I uploaded mine: [(https://goo.gl/AMuZUb)]

**Comment by coczero** [comment]
I can reproduce the bug, I'll try to find a fix but I actually have no idea what the problem is.
The csv file is parsed fine, but for some reason it can't be displayed.

**Comment by coczero** [comment]
I am pretty sure it has something to do with malformed rows of the csv file. Probably some encoding bullshit. Can't seem to find a fix tho :(

**Comment by lucianasena** [comment]
Ok :(

**Comment by rootion** [comment]
I got some spare time today and did a bit of testing with versions 1.18, 1.19. Maybe we can shed some light on the issue.

### 1.18

**What works:** 
I can successfully parse the CSV file from @lucianasena in 1.18.0.0 and all the scrobbles can be displayed in the list. It shows 52198 rows. 

**What doesn't work**
When I click in “select all” the program becomes unresponsive.

I tested a smaller version of the file, with 970 rows. It parsed the file very quick and it also managed to select all the files. It also scrobbled all files successfully in a test account.

- Is there a maximum amount of rows that the program can process? 
- Do you have any idea what is the reason for the program to crash?
- I couldn't find a log file in this version.. is there one?

Also when I opened the CVS file in Libre Office in order to make it smaller, it asked me which character set, I chose UTF-8, but it had another by default, Western Europe ISP 8859. Is this relevant?


### 1.19

**What works**
Nothing yet

**What doesnt work**
The program cant parse the CSV file anymore. It gets stuck in `Reading CSV file…`
However, even though the program becomes unresponsive and eventually shuts itself down, the log file says `Successfully parsed CSV file. Parsed 52198 rows`. 

- Why?

**Comment by coczero** [comment]
Firstly, thanks for putting your time and effort into this.
Knowing it works in 1.18 is good information. I'll try to find out what changed and caused the bug. (I could already rule out external package versions)

About your problems with 1.18: When you click "Select All" it just takes a while to select all of the records. I might be able to optimize this part, but it just takes a while for that many rows. The more rows the longer the "Select All" process will take. And yes, there is no logging in 1.18. I'm not 100% sure about encoding but I want to make encoding settable in the future anyways so it shouldnt be a problem. (I already tested all encodings and the csv file could still not be displayed in 1.20)

About 1.19: The csv file is actually parsed successfully, it just can't be displayed. When I removed the control that displayed the rows the program did not get unresponsive. Apparently something changed between 1.18 and 1.19 that causes this bug. I'll have to look further into it.

**Comment by rootion** [comment]
I have to give an update again, as I continued testing:

All versions (1.18, 1.19 and 1.20) can parse and scrobble a file that has up to 5000 rows. I tried different amount of rows for all these versions, and eventually they crash, I don't know yet the reason, but 5000 rows is a number that all of them can parse.

And because there is a limitation on 2800 scrobbles per day, a workaround would be to directly add in the documentation that if the CVS file has more than those rows, that users should first split the file into smaller chunks using for example [filesplit](http://filesplit.org/) as you suggested, and that would work in all the versions of your software, doing one chunk a day.

Unfortunately for me, as I have been scrobbling since 2006, that would mean that I would end up importing my last.fm scrobbles in 50 days ( •_•)

**Comment by coczero** [comment]
I actually identified the cause of the bug. A recent change in my scrobble display listview style has caused the listview to disable its virtualization. Basically what happens is that all 50000 items are loaded at once and the application can't keep up. I think I can work around this, I just need some days figuring it out.

**Comment by coczero** [comment]
I think I fixed it. Could you try with this attached version please?
[Debug.zip](https://github.com/coczero/Last.fm-Scrubbler-WPF/files/2480631/Debug.zip)

**Comment by rootion** [comment]
That works very smooth. Good job!

**Comment by lucianasena** [comment]
Thank you! Although, when I try to scrobble my 52192 tracks, it gives an error saying that these tracks would break the daily scrobble cap. Hahaha, I didn't even know that existed.

**Comment by coczero** [comment]
Its there since a few versions. Some people scrobbled so many tracks that it caused outages of the last.fm server. The last.fm dev team contacted me directly and made me implement a scrobble limit ^^
