### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by dlxfuentes** [coczero/Last.fm-Scrubbler-WPF#62]
Can't login to my account, get the "Failed to log in or authenticate!" message. I think this may be due to having an underscore in my username. When trying to use the Paste Your Taste function I get a fatal error with my username displayed without the underscore, so I think this may be the issue.

**Comment by coczero** [comment]
I tried to reproduce this with a username that has an underscore in it and it worked fine.
My guess is that youre using the wrong version, which would also explain why you can't login.
Please download the newest version from the release section on Github.

**Comment by chrissymay** [comment]
I am also getting the  "Failed to log in or authenticate!" message.

**Comment by coczero** [comment]
Which version are you using?

**Comment by chrissymay** [comment]
I had both the beta 1.19 and master version downloaded and was trying to use the beta 1.19. I removed all the files and downloaded the beta again and it now seems to be working. Thanks.
