### ISSUE TITLE
Scrobble album artist in iTunes

### ISSUE THREAD

**Issue by DwarfeDNL** [coczero/Last.fm-Scrubbler-WPF#63]
Hi there,

Would it be possible to add te possibility to scrobble the _Album artist_ in iTunes.

For manual scrobbling it is already implemented, but it ain't working when you scrobble something from iTunes.

Thanks in advance,
Matthijs

**Comment by coczero** [comment]
It actually is implemented, but for whatever reason (probably a bug in iTunes) the album artist can't be read for some artists. Just make sure that you are using the most up-to date version of iTunes. I just tried it with one track and the album artist could be read.
