### ISSUE TITLE
CSV Import/Export

### ISSUE THREAD

**Issue by TaNoRGoSS** [coczero/Last.fm-Scrubbler-WPF#64]
How can I import from my old account to the new all scrobblers (if there is a limit on scrobbling in 2k)?

**Comment by coczero** [comment]
Well you have to split your csv files and then just upload 2800 songs everyday

**Comment by TaNoRGoSS** [comment]
Ok, how do that? (split CSV)

**Comment by coczero** [comment]
You can use http://filesplit.org/

**Comment by TaNoRGoSS** [comment]
Thx you!
