### ISSUE TITLE
Opening the program in windows 10

### ISSUE THREAD

**Issue by sol-paul** [coczero/Last.fm-Scrubbler-WPF#65]
I can't see any file in the download that looks like it can be opened by my windows 10 device. Am I missing something. Which file links to the program?

**Comment by coczero** [comment]
Download it from here: https://github.com/coczero/Last.fm-Scrubbler-WPF/releases

**Comment by sol-paul** [comment]
Thanks I definitely was downloading the master file. Thanks for your help :)
