### ISSUE TITLE
Apple Music CSV ISSUES

### ISSUE THREAD

**Issue by musmics** [coczero/Last.fm-Scrubbler-WPF#66]
![immagine 5](https://user-images.githubusercontent.com/45818701/49865820-39eea480-fe06-11e8-9a5f-6fa9550b2686.png)

I requested the CSV file to Apple for my Plays info and I uploaded it on the Software, but as you can see the artists and the albums are all messed up. What can I do?

**Comment by coczero** [comment]
Hi, first off you should remove the header entry from your csv (you don't have to do that but it will get parsed and not be usable).
Secondly you can use the "Settings" button in the top right to configure which cell index in you csv is the artist cell etc..
