### ISSUE TITLE
iTunes Scrobbler Glitch

### ISSUE THREAD

**Issue by george-emerald** [coczero/Last.fm-Scrubbler-WPF#67]
The iTunes scrobbler gives me the following error when trying to connect: "Unable to cast COM object of type..."

**Comment by coczero** [comment]
Reinstall itunes.
This error message is always a problem with iTunes itself

**Comment by george-emerald** [comment]
Reinstalled and I get the same error. Why did you close it?

**Comment by coczero** [comment]
I closed it because this is not a Scrubbler bug.
Check this issue: https://github.com/coczero/Last.fm-Scrubbler-WPF/issues/46

**Comment by george-emerald** [comment]
Well thanks, but I don't know how to modify the registry. I googled it and opened regedit, but how do I search for that particular thing and delete it?
