### ISSUE TITLE
Feature request: Allow the user to provide their own Last FM API key

### ISSUE THREAD

**Issue by diamondavocado** [coczero/Last.fm-Scrubbler-WPF#70]
The daily scrobbling limit is extremely limiting when (like me) you have a large iTunes library backlog of 5,000 songs - each with multiple plays - which you want to scrobble. 

I understand Last.FM blacklisted your old API key because of excessive usage, however if each user could supply their own API key without recompiling the project this would not be a problem.

**Comment by coczero** [comment]
Thats not a bad idea actually!
I can implement this.

**Comment by coczero** [comment]
Sorry, I think it is a better idea not to do this.
