### ISSUE TITLE
Feature Request: Allow editing of Friend Scrobbles, before submitting.

### ISSUE THREAD

**Issue by XBagon** [coczero/Last.fm-Scrubbler-WPF#71]
I wanted to edit my own scrobble, cause the artist name was messed up, but it didn't seem like there was an option for editing it before re-submitting my scrobble.

**Comment by coczero** [comment]
Yea, this could be useful.

**Comment by coczero** [comment]
Fixed in https://github.com/coczero/Last.fm-Scrubbler-WPF/commit/2e2c6fce556e9ef31ef67faaa58a05cf29148a90
