### ISSUE TITLE
Accents not recognized

### ISSUE THREAD

**Issue by awsms** [coczero/Last.fm-Scrubbler-WPF#74]
Hi devs, I'm a French user and accents (é,à,è etc) which are really common in my language.

And when I export my scrobbles to a .CSV, they are replaced by "Ã©", "â—ˆ", "ðŸ‘¾"

Could you do something about it ? Like adding the ISO 8859 code?

**Comment by coczero** [comment]
Hi, can you give me an example user name so I can test this?
