### ISSUE TITLE
Parsing the iTunes Apple Music Play Activity.csv

### ISSUE THREAD

**Issue by SammyTeee** [coczero/Last.fm-Scrubbler-WPF#76]
Hey! I've got my history of Apple Music that I've wanted to upload. Thought this software is probably the best way of doing so. However, Apple layout the CSV with lots of unnecessary data.

How would I got about getting this into the software?

I'll include a pastebin of a snippet of the file, the whole file is just shy of 40k lines: https://pastebin.com/iwqezA2e

**Comment by coczero** [comment]
If you know which field has which id (0 being the first row, 1 being the second, 2 being the... etc) you can configure the CSV parser to only parse these specific fields. To do that click "Settings" in the CSV Scrobbler tab and adjust the indexes.
