### ISSUE TITLE
Issues with bulk scrobbling on versions newer than 1.18

### ISSUE THREAD

**Issue by zinec** [coczero/Last.fm-Scrubbler-WPF#78]
This is mostly two errors: First one will be when i use either database or CSV scrobbling and I get a prompt like this
![image](https://user-images.githubusercontent.com/46370392/55441809-63743d00-5569-11e9-954e-ba3258c00987.png)
I get this every time i use CSV and database scrobbling, and I haven't had a single case without this issue
![image](https://user-images.githubusercontent.com/46370392/55441910-a33b2480-5569-11e9-9118-61671fbadcf0.png)
This is what happens when I try to scrobble in any method that I choose to use, no matter what I do, I get this fatal error.
On other versions, most notably 1.19 and 1.20, the program is highly susceptible to crashing and freezes from any kind of input. Luckily, that doesn't seem to be the case for me on the newest version.

**Comment by coczero** [comment]
Can you provide full error infos please?
Save the text file with the rows that could not be parsed and upload it here together with the csv file youre using.
Also, this prompt should not come when using the Database Scrobbler, since that does not parse a file.

**Comment by dioleev** [comment]
Same stuff. Here are some rows that could not be parsed https://yadi.sk/d/MfhWh839ywM6dA and the file https://yadi.sk/d/g2c6FaXVO-azoQ

**Comment by dioleev** [comment]
What's up with the 'cached' error? I'm using 1.21.

**Comment by zinec** [comment]
i meant the file scrobbler, not database. also saving the text file does
nothing, doesnt create any file.

**Comment by coczero** [comment]
File scrobbling works fine with me.
Please completely remove the Scrubbler and redownload it.

**Comment by dioleev** [comment]
I slept over night and was able to scrub another 2800. Maybe it's somehow related to time? Before I got the error I tempered with date settings on my PC. As a result I scrubbed over 2000 entries with timestamps in the future.

**Comment by dioleev** [comment]
Just noticed that my browser plugin doesn't scrub as well. So it looks like last.fm blocks scrubs because some reason.

**Comment by zinec** [comment]
yeah, my account just got banned for a day because i was batch scrobbling

**Comment by dioleev** [comment]
@zinec I've been batching for a week now and it's all good. The only time I couldn't scrub is when I batched some tracks with timestamps in the future.

**Comment by zinec** [comment]
yeah seems like it was all good when it comes to batch scrobbling, no
errors like usual until i got banned
