### ISSUE TITLE
iTunes Scrobbling Error

### ISSUE THREAD

**Issue by george-emerald** [coczero/Last.fm-Scrubbler-WPF#79]
![image](https://user-images.githubusercontent.com/42093089/56166670-3c276200-5fa4-11e9-9363-8465cdd8e42d.png)

I've had this issue before on my previous laptop and I was told to reintall iTunes and that didn't fix it. It worked fine on my current laptop until I reintalled Windows and now I get the same error.

**Comment by coczero** [comment]
Please read through this: https://github.com/coczero/Last.fm-Scrubbler-WPF/issues/46

**Comment by george-emerald** [comment]
The only version of iTunes I can find is the Microsoft Store one, it's the one apple links on their site.

**Comment by george-emerald** [comment]
I tried installing from softonic and now when I try to connect the scrobbler to iTunes it crashes and I have to kill it from Task Manager.
