### ISSUE TITLE
Problems parsing CSV file

### ISSUE THREAD

**Issue by marsmallos** [coczero/Last.fm-Scrubbler-WPF#80]
Hey,

Thanks for the nice app! I have an issue with some tracks I try to scrobble. I downloaded them from my old account using the download CSV feature in the app. However some of them were not possible to parse in the CSV scrobbler and were exported to a separate text file. Here are some examples:

CSV line number: 153,Ludwig van Beethoven,Beethoven: The Complete Piano Sonatas,Piano Sonata No. 28 in A major, Op. 101: I. Etwas lebhaft und mit der innigsten Empfindung,2019-04-15 12:58:35 +00:00,,,Det går inte att parsa rad 152 med hjälp av nuvarande Delimiters.
CSV line number: 159,Ludwig van Beethoven,Beethoven: The Complete Piano Sonatas,Piano Sonata No. 27 in E minor, Op. 90: I. Mit Lebhaftigkeit und durchaus mit Empfindung und Ausdruck,2019-04-15 12:03:00 +00:00,,,Det går inte att parsa rad 158 med hjälp av nuvarande Delimiters.
CSV line number: 174,Robert Schumann,Piano Book (Deluxe Edition),Album fÃ¼r die Jugend, Op. 68 / Part 1: FÃ¼r Kleinere: 8. Wilder Reiter,2019-04-10 21:16:56 +00:00,,,Det går inte att parsa rad 173 med hjälp av nuvarande Delimiters.

Do you know what the issue is and how I can fix it?

Thanks!

**Comment by coczero** [comment]
I am currently working on improving encoding stuff for csv parsing, I hope this will be fixed with the next update.

**Comment by marsmallos** [comment]
Super! Looking forward. I will try again when the next update is released. I listen to classical music so there are a bunch of weird titles with commas and colons and quotes and german s:s and so on that I can test.

**Comment by coczero** [comment]
Hey, I'm currently testing the improved csv parsing, can you send me your csv file for testing?

**Comment by marsmallos** [comment]
Hello! I only just now saw that you had requested my csv file. Here it is: https://gofile.io/?c=Xb2Ef6

For me I get parsing errors with a lot of the Beethoven tracks.

**Comment by coczero** [comment]
Hi, I just released a new version with new configuration options for the csv scrobbling, you should try it out :)
