### ISSUE TITLE
Artists/songs/titles with special characters not urlencoded

### ISSUE THREAD

**Issue by patrickhlauke** [coczero/Last.fm-Scrubbler-WPF#81]
A minor thing, but when there are characters that are not "url safe" (like `#` or `/`) the links to the song/album don't work correctly, and the artwork isn't loaded correctly. This may also affect actual scrobbles (if it's the artist or song title), but admittedly I've not tested this aspect...

![Capture](https://user-images.githubusercontent.com/895831/58746614-f80af680-8457-11e9-952c-fbbd924d8b0a.PNG)

Example: Album title "Origin # 03" https://www.last.fm/music/Solar+Fields/Origin+%23+03 - Scrubbler opens a link to https://www.last.fm/music/Solar+Fields/Origin+#+03 which 404s (and this is likely also where it's trying to grab the album art from)

**Comment by patrickhlauke** [comment]
That particular scrobble did show correctly on my profile, but I suspect it's because it's just the artist/track title that count there, and they didn't have the special char.

![Capture](https://user-images.githubusercontent.com/895831/58746652-63ed5f00-8458-11e9-94c2-0dfbb5ee490f.PNG)

**Comment by coczero** [comment]
Yes this is on my todo.
Its only for the links though, the actual scrobbles are fine.

**Comment by patrickhlauke** [comment]
Ah, cool stuff :+1:
