### ISSUE TITLE
Import setlists from Setlist.fm

### ISSUE THREAD

**Issue by hans-juergen** [coczero/Last.fm-Scrubbler-WPF#9]
Hi, a nice feature would be to import specific setlists from Setlist.fm. I was watching 3sat live concerts during the last days on German TV and from their mediathek and thought it would be great if I could just look up the setlists of these concerts on Setlist.fm and scrobble them.

I think they have an API, too, as there also is another related app for Last.fm which can scrobble future events that you want to visit from there called Setlist Scrobbler by a former Last.fm developer:

http://sls.ffey.co/

**Comment by coczero** [comment]
Hey so I am pretty far with this feature but I just noticed the setlist.fm API does not give you the album info of songs. Do you know if this was the same way with the website you mentioned?

**Comment by hans-juergen** [comment]
Great to hear, thank you. I'm pretty sure that it was always the same, as that former Last.fm developer also used the setlist.fm API. And it is not unusual that album info is missing, as many songs have been published on several releases anyhow. If possible, one could guess that in this case a live album would be the best option.
