### ISSUE TITLE
Creating and using CSV file

### ISSUE THREAD

**Issue by James-W2** [coczero/Last.fm-Scrubbler-WPF#92]
I created a CSV file for an album so I don't have to enter the info manually each time.  See attached. I found out the hard way that I have to leave column D blank in order for album artist to be scrobbled.  Otherwise Duration would be placed in the album artist column and Last.fm would consider the duration as the artist's name!  Album artist had to go into column E and duration in column F. After I figured this out, I was able to scrobble okay.

Only other issue was when I had apostrophe in track title in CSV, it scrobbled as question mark. Is there a symbol to use to make apostrophe show correctly in scrobble?
![Ogmund-1](https://user-images.githubusercontent.com/28333950/71504711-569e2480-282f-11ea-93ad-768b8b62047c.PNG)

**Comment by coczero** [comment]
Hi, do you have the "Has Field Enclosed In Quotes" setting enabled?
And you do not have to change the order of the data in the csv file, you can configure the csv parser settings. If you still have problems, please send me the csv file so I can take a look.

**Comment by James-W2** [comment]
Thanks!  I couldn't find the "Has Field Enclosed in Quotes" setting.  However, I took the quotes off the track titles with commas and titles scrobbled properly.  I used the Import Mode so as not to deal with timestamps, especially if have to manually add them.

**Comment by coczero** [comment]
There is a settings button next to the parser selection.
