### ISSUE TITLE
File Parse Scrobbling from CSV with commas & quotes not scrobbling properly

### ISSUE THREAD

**Issue by James-W2** [coczero/Last.fm-Scrubbler-WPF#93]
As Readme indicates titles with delimiter [comma in this case] "NEED to be enclosed by quotes if the field contains any of the set delimiters," this is what I did for track 5 of the enclosed example CVA file.  However, as noted for this track in the scrubbler, anything **_after_** the comma was deleted and 4 quote signs precede the title.  See screenshot.  Do the French accent marks interfere with the process?  Also the added quotes are included in the Last.fm scrobble, in effect making this a new title with its own title page.  So I have the choice of manually doing the scrobble, doing it as a CSV without the comma, or having quotes in the title (if that will work at all). I upgraded to version 1.22.
![CVA](https://user-images.githubusercontent.com/28333950/77139322-c7219f80-6a32-11ea-89de-305753e8789b.PNG)
![CVA2](https://user-images.githubusercontent.com/28333950/77139343-da346f80-6a32-11ea-9a24-84d646f66077.PNG)

**Comment by coczero** [comment]
Did you set the "Has fields enclosed in quotes" setting enabled in the csv parser settings?

**Comment by James-W2** [comment]
I have since done further research and have now checked the "Has fields enclosed in quotes" setting. I'm now able to scrobble track titles with commas and without the quotes.  Appears I can keep this field checked in settings with or without tracks having quotes without problems.
