### ISSUE TITLE
Impossible to login (any version)

### ISSUE THREAD

**Issue by WeabooSlayer666** [coczero/Last.fm-Scrubbler-WPF#94]
When i try to log in always a pop-up shows up saying "Failed to log in or authenticate!", i'm already tried not using characters with caps and i tried downloading older versions and reinstaling the current one but still got the same problem, please help.
 the concept of the plugin is really good by the way, you should just fix those bugs.

![image](https://user-images.githubusercontent.com/63133064/78415962-94af9f00-75fb-11ea-98b7-6b73f7a58205.png)

**Comment by coczero** [comment]
Must either be a problem on last.fm's side or of one of the libraries I use.
This has worked since forever and has just now started to not work.

**Comment by WeabooSlayer666** [comment]
yeah, thank you anyway, i'll wait for updates

**Comment by coczero** [comment]
[Debug.zip](https://github.com/coczero/Last.fm-Scrubbler-WPF/files/4460876/Debug.zip)
Can you try with this version please?

**Comment by WeabooSlayer666** [comment]
> [Debug.zip](https://github.com/coczero/Last.fm-Scrubbler-WPF/files/4460876/Debug.zip)
> Can you try with this version please?

I just tested and still got the same issue, also i tried log in a different account but nothing has changed :/ 

![image](https://user-images.githubusercontent.com/63133064/79033985-0ef69b00-7b89-11ea-8a38-aae8927c045e.png)

**Comment by coczero** [comment]
Thats weird, I have no problem logging in with this version :/
Are the accounts youre using maybe set to private on last.fm?
Can you try to login on another 3rd party last.fm tool? OpenScrobbler for example (https://openscrobbler.com/)

**Comment by WeabooSlayer666** [comment]
just tried that out too, in open scrobbler i could log in naturally with no issues also i checked my account and is not set to private, maybe is a problem with my PC ?

**Comment by coczero** [comment]
Hmm, thats really weird.
Could you maybe try to just create a new test account and see if you can login with that?

**Comment by WeabooSlayer666** [comment]
nvm, for some reason it worked today, i didn't do anything it just worked out, it was really weird...
but anyway thank you for the support and for being so attentive with that.
happy easter :) 

_i'll let the thread open for now just in case_

![g](https://user-images.githubusercontent.com/63133064/79083362-3b82f200-7d04-11ea-891b-57be75476f7a.png)

**Comment by coczero** [comment]
Very strange, but glad it's working now.
I will close this issue because at this point in time there is no information about if this was a software bug, last.fm bug or anything else :)
