### ISSUE TITLE
Add "Album Artist" to CSV Downloader format

### ISSUE THREAD

**Issue by RudeySH** [coczero/Last.fm-Scrubbler-WPF#95]
Without the Album Artist field, it's impossible to tell from the CSV if multiple artists share an album (e.g. a compilation). Can this field be added?

Interestingly, the README currently already claims that the Album Artist is already in the format, but it's not, I've checked the code.

**Comment by coczero** [comment]
This is unfortunately not possible, as the last.fm api does not provide this information when getting the recent scrobbles.

**Comment by coczero** [comment]
And yes, there is a field in the csv for the album artist, but it will always be empty.

**Comment by RudeySH** [comment]
That's unfortunate. I was starting to wonder why other Last.fm data export tools had similar limitations.

> And yes, there is a field in the csv for the album artist, but it will always be empty.

I see, it's between timestamp and duration, but duration also appears to be empty all the time, so the CSV really only has 4 fields at the moment.

**Comment by coczero** [comment]
Yea, the api is kinda wonky in some parts and I think things like duration are unused but are still returned by the api.
